### ISSUE TITLE
Problem with attribute 'int' from numpy

### ISSUE THREAD

**Issue by AgustinSolano** [jkosciessa/eBOSC_py#2]
Hello, I am using the package with numpy version 1.26 and I had issues with the numpy.int attribute. I got this message (error):

> AttributeError: module 'numpy' has no attribute 'int'.
> `np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
> The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
> https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

This applies for some lines from BOSC.py script, that I changed accordingly:

```
x = np.array(list(map(np.int, x))) --> x = np.array(list(map(int, x)))

detected = np.array(list(map(np.int, detected))) --> detected = np.array(list(map(int, detected)))
```
With these changes it works but I don't know if I would have any troubles in the future.

Thanks!

**Comment by jkosciessa** [comment]
Thanks for catching this @AgustinSolano! Do you want to commit your changes and submit a pull request, or would you prefer if I update the code?
